services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: python run.py
    plan: free
    branch: main  # ou le nom de ta branche Git
    autoDeploy: true
